name: pictify
description: A new flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  ffi: ^1.1.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.pictify
        pluginClass: PictifyPlugin
      ios:
        pluginClass: PictifyPlugin

